# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Linespec < Formula
  desc "LineSpec - Provenance Records and Integration Testing"
  homepage "https://github.com/livecodelife/linespec"
  version "3.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/livecodelife/linespec/releases/download/v3.3.1/linespec_3.3.1_darwin_amd64.tar.gz"
      sha256 "06d83c20ddf560869a39b90396a1cb60e3f370adcc118c8772959337fe923744"

      define_method(:install) do
        bin.install "linespec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/livecodelife/linespec/releases/download/v3.3.1/linespec_3.3.1_darwin_arm64.tar.gz"
      sha256 "c8084d52f6e91d151e071048ba3d1d649c47c60919efd9854e506d8f702531a7"

      define_method(:install) do
        bin.install "linespec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v3.3.1/linespec_3.3.1_linux_amd64.tar.gz"
      sha256 "74617e58ef2b296c1ab89ae9e186e038ba7d390798ea45052dcc815c246632db"
      define_method(:install) do
        bin.install "linespec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v3.3.1/linespec_3.3.1_linux_arm64.tar.gz"
      sha256 "56938c12eb7502207c442e363495635922db759a6c03f87dca6b2def9c0e6a7c"
      define_method(:install) do
        bin.install "linespec"
      end
    end
  end

  def post_install
    begin
      system "#{bin}/linespec", "build"
    rescue BuildError
      opoo "Could not build linespec:latest Docker image. Docker may not be running. Run `linespec build` manually after starting Docker."
    end
  end

  test do
    system "#{bin}/linespec", "provenance", "--help"
  end
end
