# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Linespec < Formula
  desc "LineSpec - Provenance Records and Integration Testing"
  homepage "https://github.com/livecodelife/linespec"
  version "3.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/livecodelife/linespec/releases/download/v3.11.0/linespec_3.11.0_darwin_amd64.tar.gz"
      sha256 "114fb7632573024ce78285bd291dd808c9f2ed77cdfec0171945e9526c658e52"

      define_method(:install) do
        bin.install "linespec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/livecodelife/linespec/releases/download/v3.11.0/linespec_3.11.0_darwin_arm64.tar.gz"
      sha256 "1d1de95b28c7f7172705e0e22d21a35d891c10b695ca36752ad5f6b1abf9631d"

      define_method(:install) do
        bin.install "linespec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v3.11.0/linespec_3.11.0_linux_amd64.tar.gz"
      sha256 "23b2d87e061adb45bfcbbaed06163f490d98309a0585aa3552712674df6f4e3b"
      define_method(:install) do
        bin.install "linespec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v3.11.0/linespec_3.11.0_linux_arm64.tar.gz"
      sha256 "2499358704d5a83e129ee0eac260cebab0de56cc8dc681de0412a6d6ba9550fc"
      define_method(:install) do
        bin.install "linespec"
      end
    end
  end

  def post_install
    begin
      system "#{bin}/linespec", "build"
    rescue BuildError
      opoo "Could not build linespec:latest Docker image. Docker may not be running. Run `linespec build` manually after starting Docker."
    end
  end

  test do
    system "#{bin}/linespec", "provenance", "--help"
  end
end
