# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinespecBeta < Formula
  desc "LineSpec (Beta) - Provenance Records + Integration Testing"
  homepage "https://github.com/livecodelife/linespec"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/livecodelife/linespec/releases/download/v1.0.3/linespec-beta_1.0.3_darwin_amd64.tar.gz"
      sha256 "63495bebdc7912f5698316997607f653d6868b973e8c86a861452fe6a6283407"

      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/livecodelife/linespec/releases/download/v1.0.3/linespec-beta_1.0.3_darwin_arm64.tar.gz"
      sha256 "4207648469add8135201ba4ad88d1f365bf2db0863e9dc16638baec39794acef"

      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v1.0.3/linespec-beta_1.0.3_linux_amd64.tar.gz"
      sha256 "2855ba9c792e2d98da5122af037bac0fe1ec41c7536378af53066753038e94e0"
      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v1.0.3/linespec-beta_1.0.3_linux_arm64.tar.gz"
      sha256 "9be5337e8413bb738161a171ccddae305c931844a4dee0528c37a77be9f626dc"
      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
  end

  test do
    system "#{bin}/linespec", "provenance", "--help"
  end
end
