# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Linespec < Formula
  desc "Provenance Records - Structured YAML artifacts for documenting architectural decisions"
  homepage "https://github.com/livecodelife/linespec"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/livecodelife/linespec/releases/download/v1.4.0/linespec_1.4.0_darwin_amd64.tar.gz"
      sha256 "827fffd435d6845cc6727f770cd6f75c98f64f53baeac21fc1b300aaa2e1da02"

      define_method(:install) do
        bin.install "linespec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/livecodelife/linespec/releases/download/v1.4.0/linespec_1.4.0_darwin_arm64.tar.gz"
      sha256 "2c2ca2121a92643499619c5c812f4e56a35b15f7f44d91111909a5b4cf44a34c"

      define_method(:install) do
        bin.install "linespec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v1.4.0/linespec_1.4.0_linux_amd64.tar.gz"
      sha256 "7164aa48d3492b62693dc88321210ff85070811eeeae99f8aa9dc1532d96344e"
      define_method(:install) do
        bin.install "linespec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v1.4.0/linespec_1.4.0_linux_arm64.tar.gz"
      sha256 "b69e8ed963ef6cd187a4d8a333516727731a2d6964c2ad9294980c79d89d6689"
      define_method(:install) do
        bin.install "linespec"
      end
    end
  end

  test do
    system "#{bin}/linespec", "provenance", "--help"
  end
end
