# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinespecBeta < Formula
  desc "LineSpec - backward-compatible alias for the linespec formula (same binary since v2.0.0)"
  homepage "https://github.com/livecodelife/linespec"
  version "2.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/livecodelife/linespec/releases/download/v2.4.1/linespec-beta_2.4.1_darwin_amd64.tar.gz"
      sha256 "4ff2d3830e25c2f9c1bbe1c31c83a36b12a15bce33db1cf049c8bea531c08e21"

      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/livecodelife/linespec/releases/download/v2.4.1/linespec-beta_2.4.1_darwin_arm64.tar.gz"
      sha256 "c42f4b87511ce13e2cc11a0b6b0a42b294dd0caa1ec99c011a3881103bf61f0d"

      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v2.4.1/linespec-beta_2.4.1_linux_amd64.tar.gz"
      sha256 "3540cd9ae241ef7dca0f0cba7b2a5f99fc5838973ab1b831d95e98265424f48b"
      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v2.4.1/linespec-beta_2.4.1_linux_arm64.tar.gz"
      sha256 "af70d557234075a9167db029d456c43306969c33abfb1bd69a0c13968baa9242"
      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
  end

  test do
    system "#{bin}/linespec", "provenance", "--help"
  end
end
