# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinespecBeta < Formula
  desc "LineSpec - backward-compatible alias for the linespec formula (same binary since v2.0.0)"
  homepage "https://github.com/livecodelife/linespec"
  version "3.11.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/livecodelife/linespec/releases/download/v3.11.5/linespec-beta_3.11.5_darwin_amd64.tar.gz"
      sha256 "f9f9e6f16c25e2b20775d60ab5ac215464f4ddebc1d7b14cc68e1e92acbfec99"

      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/livecodelife/linespec/releases/download/v3.11.5/linespec-beta_3.11.5_darwin_arm64.tar.gz"
      sha256 "2124819f757b84b4bd993bc3ab16bc38f88ceeea5043cd97e6df68daa4c8f279"

      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v3.11.5/linespec-beta_3.11.5_linux_amd64.tar.gz"
      sha256 "93627c1b65b8c1e057f079b696b24b67e3682ab2cc45bc469c9092f037bd3bca"
      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/livecodelife/linespec/releases/download/v3.11.5/linespec-beta_3.11.5_linux_arm64.tar.gz"
      sha256 "a321ddf168a8d052123d77cf5e0592f98fecd03fb19f023b18d3ea6daecdfe3c"
      define_method(:install) do
        bin.install "linespec" => "linespec-beta"
      end
    end
  end

  test do
    system "#{bin}/linespec", "provenance", "--help"
  end
end
